### ISSUE TITLE
API Key is incorrect

### ISSUE THREAD

**Issue by waziaq** [AfterShip/apps-opencart#18]
After I install the plugin on OC 3.0.3.6. I try to insert the API key and username. when save have an error say 'API Key is incorrect'. But when I try using another API from another account can use it.

**Comment by yangyao** [comment]
Can you provide you aftership account email  ? . our support team will help you to solve this issue . @waziaq 

Our email : apps@aftership.com

**Comment by waziaq** [comment]
> Can you provide you aftership account email ? . our support team will help you to solve this issue . @waziaq
> 
> Our email : [apps@aftership.com](mailto:apps@aftership.com)

I already sent an email to your support. Please check it.

**Comment by yangyao** [comment]
Our support has receive the message , will close this issue. fell free to re-open it. if have any question.
